#!/bin/bash -e

mvn clean

echo "(System/exit 0)" | ./shen.java
echo

mvn package -DskipTests=true

test_classpath="target/test-classes:`find . -name shen.java-*-standalone.jar`"

time yes | java $JAVA_OPTS -Xss6m -cp $test_classpath shen.TestProgramsTest 2>&1 | tee test.log
grep -q "failed; continue? (y/n)" test.log && exit 1
